<a href="https://colab.research.google.com/github/MidhulaMS/EV-Population-Prediction/blob/Anand/EV_Population_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# For evaluating Mode
from statistics import mode

# Mutual Information: Target is salary which is continous
from sklearn.feature_selection import mutual_info_regression

# For min max scaling
from sklearn.preprocessing import MinMaxScaler

# Reading Data

In [4]:
filepath = "/content/drive/MyDrive/AI ML/Data/washington_EV.csv"

In [5]:
EV_df = pd.read_csv(filepath)

## Exploratory data analysis (EDA)

In [6]:
EV_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 287763 entries, 0 to 287762
Data columns (total 16 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   VIN (1-10)                                         287763 non-null  object
 1   County                                             287754 non-null  object
 2   City                                               287754 non-null  object
 3   State                                              287763 non-null  object
 4   Postal Code                                        287754 non-null  float64
 5   Model Year                                         287763 non-null  int64
 6   Make                                               287763 non-null  object
 7   Model                                              287763 non-null  object
 8   Electric Vehicle Type                              287763 non-null  object
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  287763 non-null  object
 10  Electric Range                                     287754 non-null  float64
 11  Legislative District                               287023 non-null  float64
 12  DOL Vehicle ID                                     287763 non-null  int64
 13  Vehicle Location                                   287747 non-null  object
 14  Electric Utility                                   287754 non-null  object
 15  2020 Census Tract                                  287754 non-null  float64
dtypes: float64(4), int64(2), object(10)
memory usage: 35.1+ MB

### finding missing values

In [9]:
EV_df.isna().sum()

VIN (1-10)                                             0
County                                                 9
City                                                   9
State                                                  0
Postal Code                                            9
Model Year                                             0
Make                                                   0
Model                                                  0
Electric Vehicle Type                                  0
Clean Alternative Fuel Vehicle (CAFV) Eligibility      0
Electric Range                                         9
Legislative District                                 740
DOL Vehicle ID                                         0
Vehicle Location                                      16
Electric Utility                                       9
2020 Census Tract                                      9
dtype: int64

### finding duplicates

In [10]:
EV_df.duplicated().sum()

np.int64(0)

### Data Description

In [7]:
EV_df.describe()

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 Census Tract
count,287754.000000,287763.000000,287754.000000,287023.000000,2.877630e+05,2.877540e+05
mean,98174.889729,2022.207299,37.828697,28.849608,2.486886e+08,5.296750e+10
std,2638.364484,3.075325,77.223589,14.889125,6.293818e+07,1.691737e+09
min,1030.000000,1999.000000,0.000000,1.000000,4.385000e+03,1.001020e+09
25%,98052.000000,2021.000000,0.000000,17.000000,2.258425e+08,5.303301e+10
50%,98133.000000,2023.000000,0.000000,32.000000,2.658514e+08,5.303303e+10
75%,98387.000000,2024.000000,32.000000,42.000000,2.820231e+08,5.305394e+10
max,99801.000000,2027.000000,337.000000,49.000000,4.791150e+08,6.601095e+10

## Univariate Analysis :analyze and understand the distribution, characteristics, and patterns of a single variable in a dataset

In [ ]:
for cols in EV_df.select_dtypes(include="number"):
  sns.histplot(EV_df[cols])

### Correlation Matrix

# Data preprocessing

## Data Cleaning

### Missing Value Handling

### Duplicates Removal

## Outlier Handling

###Box plot

# Data Transformation

## Scaling

## Encoding

# Data Splitting

# Model Building